
  P.version.commit = '';
  document.write(
 '<script src="vendor/three.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/stats.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/orbit.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/hull.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/spring.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/hammer.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/instancedmesh.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/html2canvas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/engine.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/config.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/shaders.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/geometry.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/atlas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/scene.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/camera.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/navigation.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/animation.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/gestures.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/instances.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/culling.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/pointer.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/zoom.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/system/drag.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/styles/materials.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/base.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/location.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/area.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/city.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/zone.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/floor.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/icon.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/label.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/line.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/panel.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/sprite.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/underlay.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/overlay.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/wall.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/road.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/background.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/objects/index.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/interaction/canvas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/interaction/surface.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/interaction/stack.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/views/defaults.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/views/map.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/renderer.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/preload.js?ver=' + P.version.commit + '"></script>');
