
  P.version.commit = '';
  document.write(
 '<script src="vendor/three.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/stats.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/orbit.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/hull.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/spring.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/hammer.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/instancedmesh.js?ver=' + P.version.commit + '"></script>\
  <script src="vendor/html2canvas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/posit.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/version.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/config.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/shaders.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/geometry.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/atlas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/scene.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/interface.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/camera.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/navigation.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/data.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/queue.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/interface.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/animation.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/gestures.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/graph.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/instances.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/culling.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/import.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/pointer.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/snapshots.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/zoom.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/system/drag.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/base.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/location.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/area.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/zone.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/floor.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/wall.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/icon.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/label.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/person.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/furniture.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/pin.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/line.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/panel.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/sprite.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/underlay.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/overlay.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/background.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/company.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/objects/building.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/interaction/canvas.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/interaction/surface.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/interaction/stack.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/defaults.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/floor.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/graph.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/search.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/editor.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/chart.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/views/location.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/area.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/zone.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/stats.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/location.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/profile.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/pin.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/labels/company.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/materials.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/icons.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/colors.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/samples.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/sprites.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/objects.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/styles/objects.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/renderer.js?ver=' + P.version.commit + '"></script>\
  <script src="engine/src/preload.js?ver=' + P.version.commit + '"></script>');
